WebUI/Controllers/PermissionController.cs
using System;
using BusinessObjects;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DataObjects.EntityFramework;
using WebUI.Models;
using WebUI.Repositories;

namespace WebUI.Controllers
{
    public class PermissionController : Controller
    {
        private readonly IUserPermissionRepository _efUserPermissionRepository;

        public PermissionController(IUserPermissionRepository efUserPermissionRepository)
        {
            _efUserPermissionRepository = efUserPermissionRepository;
        }
        //
        // GET: /Permission/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PermissionDropDown(UserViewModel user)
        {
            var vm = new UserDelegateViewModel
            {
                PermissionSelectList = new List<SelectListItem> {
                                                        new SelectListItem{
                                                            Selected = true,
                                                            Text = User.Identity.Name,
                                                            Value = string.Empty
                                                        } }
            };

            if (Session["PermissionId"] == null || string.Empty.Equals(Session["PermissionId"].ToString()))
            {
                Session["PermissionId"] = string.Empty;
                vm.PermissionId = string.Empty;
            }
            else
            {
                vm.PermissionId = Session["PermissionId"].ToString();
            }

            //todo can not use async as this is a partialView ???
            var query = _efUserPermissionRepository.GetAllByUserId(user.UserId);
            vm.PermissionSelectList.AddRange(query.Select(x => new SelectListItem
            {
                Text = x.AspNetUser1.UserName + " as " + x.AspNetRole.Name,
                Value = x.Id.ToString(CultureInfo.InvariantCulture)
            }).ToList());

            return PartialView(vm);
        }

        public async Task<bool> SetCurrentUser(string permissionId, string returnUrl, UserViewModel user)
        {
            var userPermision = await _efUserPermissionRepository.GetUserPermissionSecureAsync(user.UserId, permissionId);
            bool hasPermission = userPermision != null;
            if (hasPermission)
            {
                Session["PermissionId"] = permissionId;
            }
            else
            {
                Session["PermissionId"] = string.Empty;
            }
            return hasPermission;
        }

        public ActionResult Edit()
        {
            return View();
        }

        public enum GivePermissionStatus
        {
            Fail, Success, AlreadyHave, NoAccount
        }
        public async Task<GivePermissionStatus> GivePermission(string email, string roleName, UserViewModel user)
        {
            //todo need email add validation

            var returnStatus =  GivePermissionStatus.Fail;
            var userId = user.UserId;

            var role = await _efUserPermissionRepository.GetRoleByName(roleName);
            if (role != null)
            {
                var actAsUser = await _efUserPermissionRepository.GetUserByEmailAsync(email);
                if (actAsUser == null)
                {
                    returnStatus = GivePermissionStatus.NoAccount;
                }
                else
                {
                    var roleId = role.Id;
                    var actAsUserId = actAsUser.Id;
                    var userPermision =
                        await _efUserPermissionRepository.GetUserPermissionAsync(userId, actAsUserId, roleId);
                    if (userPermision != null)
                    {
                        return GivePermissionStatus.AlreadyHave;
                    }

                    var vm = new UserPermission
                    {
                        Id = Guid.NewGuid().ToString(),
                        User_Id = userId,
                        ActAsUser_Id = actAsUserId,
                        Role_ID = roleId
                    };

                    _efUserPermissionRepository.Insert(vm);
                    await _efUserPermissionRepository.SaveChangesAsync();
                    returnStatus = GivePermissionStatus.Success;
                }
            }
            return returnStatus;
        }

        public async Task<bool> RemovePermission(string permissionId, UserViewModel user)
        {
            var permission = await _efUserPermissionRepository.GetUserPermissionSecureAsync(user.UserId, permissionId);
            if (permission != null)
            {
                await _efUserPermissionRepository.DeleteAsync(permission);
                return true;
            }
            return false;
        }
    }
}

WebUI/Controllers/ReceiptsController.cs
using BusinessObjects;
using DataObjects.EntityFramework;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebUI.Common;
using WebUI.Models;
using WebUI.Repositories;

namespace WebUI.Controllers
{
    [Authorize]
    public class ReceiptsController : Controller
    {
        private IReceiptRepository _efReceiptRepository;
        private readonly IUserPermissionRepository _efUserPermissionRepository;

        public ReceiptsController(IReceiptRepository efReceiptRepository, IUserPermissionRepository efUserPermissionRepository)
        {
            _efReceiptRepository = efReceiptRepository;
            _efUserPermissionRepository = efUserPermissionRepository;
        }

        #region Index page
        public ActionResult Index()
        {
            return View();
        }

        //public JsonResult AutoCompleteReceiptSearch(string id, string searchString, UserViewModel user) //todo need userId secure
        //{
        //    var list = new List<string> { "aaa", "bbb", "abc" };
        //    return Json(new { list }, JsonRequestBehavior.AllowGet);
        //}

        //todo check json attributes eg hannel json exception
        [HttpPost]
        public async Task<JsonResult> DataTableAjaxHandler(DataTablesParam param, UserViewModel user)
        {
            var userId = await ImpersonateCheckAsync(user.UserId);
            var recieptBriefList = await _efReceiptRepository.GetReceiptBriefsByUserIdAsync(userId);

            var json = GenerateJsonContent(recieptBriefList);
            var jsonString = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = recieptBriefList.Count(),
                iTotalDisplayRecords = 3,
                aaData = json
            });

            return jsonString;
        }

        //todo possible to mave this into the userPermissionRepo
        private async Task<string> ImpersonateCheckAsync(string userId)
        {
            string id = userId;
            var permissionId = Session["PermissionId"];

            if (permissionId == null || string.Empty.Equals(permissionId.ToString()))
            {
                return id;
            }

            var userPermission = await _efUserPermissionRepository.GetUserPermissionSecureAsync(userId, permissionId.ToString());
            if (userPermission != null)
            {
                return userPermission.ActAsUser_Id;
            }

            return id;
        }

        private static List<List<string>> GenerateJsonContent(IEnumerable<ReceiptBriefViewModel> data)
        {
            return data.Select(receiptBrief => new List<string>
            {
                receiptBrief.Id.ToString(CultureInfo.InvariantCulture), 
                receiptBrief.Description, 
                receiptBrief.Vendor, 
                receiptBrief.PurchaseDate.HasValue ? receiptBrief.PurchaseDate.Value.ToString("d MMM yyyy") : string.Empty,
                receiptBrief.Price.HasValue ? receiptBrief.Price.Value.ToString("#0.00") : string.Empty, 
                receiptBrief.HasImage, 
                receiptBrief.DateEntered.ToString("d MMM yyyy"),
                receiptBrief.Status, 
                string.Empty
            }).ToList();
        }

        public async Task<ViewResult> Create(UserViewModel user)
        {
            var userId = await ImpersonateCheckAsync(user.UserId);
            var viewModel = await _efReceiptRepository.GetReceiptForEditAsync(0, userId);
            return View("Edit", viewModel);
        }

        //[HttpPost]
        public async Task<RedirectToRouteResult> Delete(ReceiptBriefViewModel receiptBrief, UserViewModel user)
        {

            if (receiptBrief.Id < 1) return RedirectToAction("Index"); //TODO LOG it

            var userId = await ImpersonateCheckAsync(user.UserId);

            var receiptViewModel = new ReceiptViewModel
            {
                Id = receiptBrief.Id,
                UserId = userId
            };
            await _efReceiptRepository.DeleteAsync(receiptViewModel);
            await _efReceiptRepository.SaveChangesAsync();

            TempData["message"] = string.Format("{0} was deleted", receiptBrief.Description);
            return RedirectToAction("Index");

        }

        #endregion

        #region Edit page

        public async Task<ViewResult> Edit(int id, UserViewModel user)
        {
            var userId = await ImpersonateCheckAsync(user.UserId);
            var viewModel = await _efReceiptRepository.GetReceiptForEditAsync(id, userId);
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(ReceiptViewModel receiptViewModel, UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var userId = await ImpersonateCheckAsync(user.UserId);
                receiptViewModel.UserId = userId;

                await UpdateVendorAsync(receiptViewModel, userId);

                //todo receiptstatus set to 1 when add new; why id start from 1000?
                if (receiptViewModel.Id == 0)
                {
                    _efReceiptRepository.Insert(receiptViewModel);
                }
                else
                {
                    await _efReceiptRepository.Update(receiptViewModel);
                }

                await _efReceiptRepository.SaveChangesAsync();

                //This is a key/value dictionary similar to the session data and view bag features we have used previously.
                //The key difference from session data is that temp data is deleted at the end of the HTTP request.
                TempData["message"] = string.Format("{0} has been saved", receiptViewModel.Description);
                return RedirectToAction("Index");
            }

            var receiptEditViewModel = await _efReceiptRepository.GetReceiptForEditViewModelAsync(receiptViewModel);
            return View(receiptEditViewModel);
        }

        private async Task UpdateVendorAsync(ReceiptViewModel receiptViewModel, string userId)
        {
            if (!string.IsNullOrEmpty(receiptViewModel.VendorName))
            {
                var vendor = await _efReceiptRepository.GetVednorSecure(receiptViewModel.VendorName, userId);
                if (vendor == null)
                {
                    var newVednor = new VendorViewModel
                    {
                        VendorName = receiptViewModel.VendorName,
                        UserId = userId
                    };
                    receiptViewModel.VendorId = 0;
                    receiptViewModel.Vendor = newVednor;
                }
                else
                {
                    receiptViewModel.VendorId = vendor.Id;
                }
            }
            else
            {
                receiptViewModel.VendorId = null;
            }
        }

        #endregion

        #region Vendor

        public async Task<JsonResult> AutoCompleteVendor(string searchString, UserViewModel user)
        {
            var userId = await ImpersonateCheckAsync(user.UserId);
            var list = await _efReceiptRepository.SearchVendorNameSecure(searchString, userId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public async Task DeleteVendor(string name, UserViewModel user)
        {
            var userId = await ImpersonateCheckAsync(user.UserId);
            await _efReceiptRepository.DeleteVendorSecure(name, userId);
            await _efReceiptRepository.SaveChangesAsync();
        }

        #endregion

        #region images

        public async Task<FileContentResult> GetImage(int imageId, UserViewModel user)
        {
            var userId = await ImpersonateCheckAsync(user.UserId);

            var image = await _efReceiptRepository.GetImageSecure(imageId, userId);
            if (image != null)
            {
                return File(image.ImageData, image.ImageMimeType);
            }

            return null;
        }

        public async Task<JsonResult> GetImages(int receiptId, UserViewModel user)
        {
            if (receiptId > 0)
            {
                var userId = await ImpersonateCheckAsync(user.UserId);
                var list = await _efReceiptRepository.GetImageAddrsByReceiptId(receiptId, userId);
                var jsonResult = Json(list, JsonRequestBehavior.AllowGet);
                return jsonResult;
            }
            return null; //todo ajax return raise error event, what's the best way to handel?
        }

        [HttpPost]
        public async Task UploadFiles(int? receiptId, string desc, IEnumerable<HttpPostedFileBase> files, UserViewModel user)
        {
            //todo need to check the receipt belong to this user
            int id = receiptId ?? 0;
            if (id <= 0)
            {
                //todo log
                return;
            }

            HttpPostedFileBase image = files.FirstOrDefault();
            if (image != null && image.ContentLength > 0)
            {
                //string savedFileName = Path.Combine(
                //  AppDomain.CurrentDomain.BaseDirectory + "Files",
                //  Path.GetFileName(image.FileName));
                //image.SaveAs(savedFileName);

                var userId = await ImpersonateCheckAsync(user.UserId);

                var receiptImage = new ReceiptImage
                {
                    ImageData = new byte[image.ContentLength],
                    ImageMimeType = image.ContentType,
                    Description = desc,
                    Date = DateTime.Now,
                    IsActive = true,
                    User_Id = userId,
                };

                image.InputStream.Read(receiptImage.ImageData, 0, image.ContentLength);

WebUI/Views/Receipts/Edit.cshtml
@model WebUI.Models.ReceiptEditViewModel

@{
    ViewBag.Title = "Edit" + @Model.ReceiptViewModel.Description;
    Layout = "~/Views/Shared/_LandlordLayout.cshtml";
}

<div class="page-header">
    <h2>Edit Receipt</h2>
</div>
@Html.ValidationSummary("Error occurred:")
<div id="panel" class="panel panel-default">
    <div class="panel-heading clearfix">
        <h3 class="panel-title pull-left">Edit Receipt - <b>@Model.ReceiptViewModel.Id</b> (Status: <b>@Model.ReceiptViewModel.ReceiptStatus</b>)</h3>
        <div class=" pull-right">
            <button class="btn btn-primary btn-sm" type="button" data-toggle="modal" data-target="#fileUploadModal">Upload Files</button>
            <button class="btn btn-primary btn-sm" type="button" data-toggle="modal" data-target="#fileUploadModal">Use Existing Files</button>
            <button class="btn btn-primary btn-sm" id="btnViewFiles" type="button">View Files</button>
        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Edit", "Receipts", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.ReceiptViewModel.Id)
            @Html.HiddenFor(x => x.ReceiptViewModel.ReceiptStatus)
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.Description)
                    @Html.TextBoxFor(x => x.ReceiptViewModel.Description, new { @class = "form-control input-sm", maxlength = 255 })
                </div>
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.PurchaseDate)
                    @Html.TextBoxFor(x => x.ReceiptViewModel.PurchaseDate, "{0:d MMM yyyy}", new { @class = "form-control input-sm", maxlength = 50 })
                </div>
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.VendorName)
                    <div class="input-group">
                        @Html.TextBoxFor(x => x.ReceiptViewModel.VendorName, new { @class = "form-control input-sm", maxlength = 50 })
                        @Html.HiddenFor(x => x.ReceiptViewModel.VendorId)
                        <span id="vendorDropDown" class="input-group-addon caretCursor"><span class="caret"></span></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xs-6 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.Price)
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        @Html.TextBoxFor(x => x.ReceiptViewModel.Price, "{0:#0.00}", new { @class = "form-control input-sm" })
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.GstRate)
                    <div class="input-group">
                        @Html.TextBoxFor(x => x.ReceiptViewModel.GstRate, "{0:#0.00}", new { @class = "form-control input-sm" })
                        <span class="input-group-addon">%</span>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.AccountTypeId)
                    @Html.DropDownListFor(x => x.ReceiptViewModel.AccountTypeId, Model.AccountTypeSelectList, string.Empty, new { style = "width: 100%" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.Reference)
                    @Html.TextBoxFor(x => x.ReceiptViewModel.Reference, new { @class = "form-control input-sm" })
                </div>
                <div class="col-xs-12 col-sm-4">
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">
                            @Html.CheckBoxFor(x => x.ReceiptViewModel.IsBulk)
                        </span>
                        @Html.LabelFor(x => x.ReceiptViewModel.IsBulk, new { @class = "form-control input-sm" })
                    </div><!-- /input-group -->
                </div>
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.CurrencyId)
                    @Html.DropDownListFor(x => x.ReceiptViewModel.CurrencyId, Model.CurrencySelectList, string.Empty, new { style = "width: 100%" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.ReceiptCategoryId)
                    @Html.DropDownListFor(x => x.ReceiptViewModel.ReceiptCategoryId, Model.CategorySelectList, string.Empty, new { style = "width: 100%" })
                    @*@Html.ListBoxFor(x => x.ReceiptViewModel.ReceiptCategoryId, Model.CategorySelectList, new { style = "width: 100%" }) //for multi select*@
                </div>
            </div>
            <br />
            @*<div class="row">  //todo add to Upload Files
                    <div class="col-xs-12 col-sm-4">
                        @Html.Label("Upload new receipt image")
                        <input type="file" name="Image" />
                    </div>
                </div>
                <br />*@
            <div class="row">
                <div class="col-xs-6 col-sm-4">
                    @Html.LabelFor(x => x.ReceiptViewModel.Note)
                    @Html.TextAreaFor(x => x.ReceiptViewModel.Note, new { @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 text-right">
                    <input class="btn btn-success btn-sm" type="submit" value="Save" />
                    @Html.ActionLink("Cancel and return to List", "Index")
                </div>
            </div>
        }
    </div>
</div>
<div class="modal fade" id="fileUploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 660px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><span class="glyphicon glyphicon-camera fontSize16"></span> Upload images or PDFs</h4>
            </div>
            <div class="modal-body" style="max-height: 350px; overflow-y: auto">
                <div id="dropzone" class="well hidden">Drop files here</div>
                <div id="bodyContent">
                    <div id="desc">
                        <h5>Attach uploaded images or PDFs to this receipt as evidence.</h5>
                        <h5>You can also drag & drop files into this dialog.</h5>
                        <h5>Attachment type can be jpg, jpeg or pdf.</h5>
                        <br />
                        <div>Having trouble? Switch to basic uploader.</div>
                    </div>
                    <div id="filelistholder" class="hidden">
                        <h5>You can give a description for each of the file upto 50 chars.</h5>
                        <table class="table table-striped">
                            <tr>
                                <th></th>
                                <th>Description (Max. 50 Chars)</th>
                                <th>File Size</th>
                                <th></th>
                                <th>Status</th>
                            </tr>
                            <tbody id="fileListTBody"></tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="progress" id="overallProgress"><div class="progress-bar" id="overallbar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"><span class="sr-only">0% Complete</span></div></div>
            <div class="modal-footer">
                <span id="footer-left" class="pull-left"></span>
                <div class="pull-right" id="footer-right">
                    <span id="btnAddFiles" class="btn btn-info fileinput-button btn-sm">
                        <i class="icon-plus icon-white"></i>
                        <span id="btnName">Add files...</span>
                        <input type="file" id="fileupload" name="files" multiple> @*ccept="image/*"*@
                    </span>
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div id="viewDragger" class="ui-widget-content hidden">
    @*todo move it to js*@
    <div id="viewerHeader">
        <h5 id="title" class="pull-left">File Viewer</h5>
        <button class="pull-right"><b>X</b></button>
        <div class="clearfix"></div>
        <hr />
    </div>
    <div id="viewerBody">
        <div id="imageViewer" class="viewer"></div>
    </div>
    <div id="viewerFooter">
        <hr />
        <label id="fileDesc"></label>
        <button id="prev" class="btn btn-sm"><</button>
        <button id="next" class="btn btn-sm">></button>
    </div>
</div>
@section Contents{
    @Styles.Render("~/Content/receipts_edit")
    @Styles.Render("~/Content/fileupload")
    @*@Styles.Render("~/bundles/fileupload/bootstrap/BasicPlus/css")*@
}
@section Scripts {
    @Scripts.Render("~/bundles/jquery-ui-min")
    @Scripts.Render("~/bundles/receipts_edit")
    @Scripts.Render("~/bundles/fileupload")
    @*@Scripts.Render("~/bundles/fileupload/bootstrap/BasicPlus/js")
        <script src="/Scripts/LMate/FileUpload.js"></script>*@
}
@section DocumentReady
{
    docReady();
    ReceiptUpload();
    //$('#fileUploadModal').modal();
}

WebUI/Views/Receipts/Index.cshtml
@{
    ViewBag.Title = "All Receipts";
    Layout = "~/Views/Shared/_LandlordLayout.cshtml";
}
@Html.Action("PermissionDropDown", "Permission")
<br/>
<h2>All Receipts</h2>
<p>@Html.ActionLink("Add a new receipt", "Create")</p>
<br />
<table id="dataTable">
    <thead>
        <tr>
            <th><input id="selectAllReceipts" type="checkbox" /></th>
            <th>Description</th>
            <th>Vendor</th>
            <th>Purchase Date</th>
            <th>Price</th>
            <th>Has Image</th>
            <th>Date Entered</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        @*<tr>
            <th></th>
            <th>Description</th>
            <th>Vendor</th>
            <th>Purchase Date</th>
            <th>Price</th>
            <th>Has Image</th>
            <th>Date Entered</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>*@
    </thead>
    <tbody></tbody>
    <tfoot>

    </tfoot>
</table>
<div>
    @*@Html.Partial("Index", Html.DataTableVm("id", (ReceiptsController h) => h.GetUsers(null)))*@
</div>

@section Contents
{
    @Styles.Render("~/Content/receipts_index")
}
@section Scripts {
    @Scripts.Render("~/bundles/receipts_index")
}

@section DocumentReady
{
    docReady();
}