WebUI/Controllers/DashboardController.cs
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Landlord/

        public ActionResult Index()
        {
            return View();
        }
    }
}

WebUI/Controllers/PermissionController.cs
using System;
using BusinessObjects;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DataObjects.EntityFramework;
using WebUI.Models;
using WebUI.Repositories;

namespace WebUI.Controllers
{
    public class PermissionController : Controller
    {
        private readonly IUserPermissionRepository _efUserPermissionRepository;

        public PermissionController(IUserPermissionRepository efUserPermissionRepository)
        {
            _efUserPermissionRepository = efUserPermissionRepository;
        }
        //
        // GET: /Permission/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PermissionDropDown(UserViewModel user)
        {
            var vm = new UserDelegateViewModel
            {
                PermissionSelectList = new List<SelectListItem> {
                                                        new SelectListItem{
                                                            Selected = true,
                                                            Text = User.Identity.Name,
                                                            Value = string.Empty
                                                        } }
            };

            if (Session["PermissionId"] == null || string.Empty.Equals(Session["PermissionId"].ToString()))
            {
                Session["PermissionId"] = string.Empty;
                vm.PermissionId = string.Empty;
            }
            else
            {
                vm.PermissionId = Session["PermissionId"].ToString();
            }

            //todo can not use async as this is a partialView ???
            var query = _efUserPermissionRepository.GetAllByUserId(user.UserId);
            vm.PermissionSelectList.AddRange(query.Select(x => new SelectListItem
            {
                Text = x.AspNetUser1.UserName + " as " + x.AspNetRole.Name,
                Value = x.Id.ToString(CultureInfo.InvariantCulture)
            }).ToList());

            return PartialView(vm);
        }

        public async Task<bool> SetCurrentUser(string permissionId, string returnUrl, UserViewModel user)
        {
            var userPermision = await _efUserPermissionRepository.GetUserPermissionSecureAsync(user.UserId, permissionId);
            bool hasPermission = userPermision != null;
            if (hasPermission)
            {
                Session["PermissionId"] = permissionId;
            }
            else
            {
                Session["PermissionId"] = string.Empty;
            }
            return hasPermission;
        }

        public ActionResult Edit()
        {
            return View();
        }

        public enum GivePermissionStatus
        {
            Fail, Success, AlreadyHave, NoAccount
        }
        public async Task<GivePermissionStatus> GivePermission(string email, string roleName, UserViewModel user)
        {
            //todo need email add validation

            var returnStatus =  GivePermissionStatus.Fail;
            var userId = user.UserId;

            var role = await _efUserPermissionRepository.GetRoleByName(roleName);
            if (role != null)
            {
                var actAsUser = await _efUserPermissionRepository.GetUserByEmailAsync(email);
                if (actAsUser == null)
                {
                    returnStatus = GivePermissionStatus.NoAccount;
                }
                else
                {
                    var roleId = role.Id;
                    var actAsUserId = actAsUser.Id;
                    var userPermision =
                        await _efUserPermissionRepository.GetUserPermissionAsync(userId, actAsUserId, roleId);
                    if (userPermision != null)
                    {
                        return GivePermissionStatus.AlreadyHave;
                    }

                    var vm = new UserPermission
                    {
                        Id = Guid.NewGuid().ToString(),
                        User_Id = userId,
                        ActAsUser_Id = actAsUserId,
                        Role_ID = roleId
                    };

                    _efUserPermissionRepository.Insert(vm);
                    await _efUserPermissionRepository.SaveChangesAsync();
                    returnStatus = GivePermissionStatus.Success;
                }
            }
            return returnStatus;
        }

        public async Task<bool> RemovePermission(string permissionId, UserViewModel user)
        {
            var permission = await _efUserPermissionRepository.GetUserPermissionSecureAsync(user.UserId, permissionId);
            if (permission != null)
            {
                await _efUserPermissionRepository.DeleteAsync(permission);
                return true;
            }
            return false;
        }
    }
}

WebUI/Views/Shared/_LandlordLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @RenderSection("Contents", required: false)
    @Scripts.Render("~/bundles/modernizr")

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="centerlised container">
        <div id="header">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("LMateLogo", "Index", "Dashboard")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
        <ul class="clear-float nav nav-tabs nav-justified" id="navigation">
            <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
            <li>@Html.ActionLink("Receipts", "Index", "Receipts")</li>
            <li>@Html.ActionLink("Permissions", "Index", "Permission")</li>
            <li>@Html.ActionLink("Rental Income", "Index", "RentalIncome")</li>
            <li>@Html.ActionLink("Inbox", "Index", "Inbox")</li>
            <li>@Html.ActionLink("User", "Index", "Account")</li>
            <li>@Html.ActionLink("Role", "Index", "Role")</li>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            @*<li>@Html.ActionLink("Applicants", "Contact", "Home")</li>
                <li>@Html.ActionLink("Tasks", "Contact", "Home")</li>
                <li>@Html.ActionLink("Contracts", "Contact", "Home")</li>
                <li>@Html.ActionLink("Bonds", "Contact", "Home")</li>
                <li>@Html.ActionLink("Tenants", "Contact", "Home")</li>
                <li>@Html.ActionLink("Properties", "Contact", "Home")</li>
                <li>@Html.ActionLink("Inspections", "Contact", "Home")</li>*@
        </ul>
        <div id="content">
            <section id="main">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }
                @RenderBody()
            </section>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
    <script>
        ////not sure why this function has to be in the _layout area not here
        //function Sortit() {
        //            var $r = $("#currentRolelist option");
        //            $r.sort(function (a, b) {
        //                if (a.text < b.text) return -1;
        //                if (a.text == b.text) return 0;
        //                return 1;
        //            });
        //            $($r).remove();
        //            $("#currentRolelist").append($($r));
        //        }

        $(function () {
            var controlerName = window.location.pathname.split('/');
            //alert(window.location.pathname + '\r\n/'+ controlerName[1]);
            $('#navigation li').removeClass('active');
            $('#navigation li a[href="/' + controlerName[1] + '"]').parent().addClass('active');

            //stateful button
            $(':input[data-loading-text]').click(function () {
                var btn = $(this);
                btn.button('loading');
                setTimeout(function () {
                    btn.button('reset');
                }, 3000);
            });

            @RenderSection("DocumentReady", required: false)
        });
    </script>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <title>@ViewBag.Title - LMate</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @Styles.Render("~/Content/frontpage")
    @RenderSection("Contents", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="centerlised container">
        <div id="header">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("LMateLogo", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
        <div class="clear-float navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">LMate</a>
            </div>
            <div class="navbar-collapse collapse" id="navigation">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Receipt", "Index", "Receipts")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Super"))
                        {
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_LoginPartial")
                    <li class="active"><a href="./">Default</a></li>
                </ul>
            </div>
        </div>
        <div id="content">
            <section id="main">
                @RenderBody()
            </section>
        </div>
    </div>
    <footer id="footer">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - LMate</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/frontpage")
    @RenderSection("Scripts", required: false);
    <script>
        $(function () {
            docReady();

            @RenderSection("DocumentReady", required: false);
        });
    </script>
</body>
</html>